# Add this snippet to the top of your playbook.
# It will install python2 if missing (but checks first so no expensive repeated apt updates)
# gwillem@gmail.com

- hosts: all
  gather_facts: False

  tasks:
  - name: install python
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  - name: install atop
    apt:
      name: atop
    become: true

  - name: install pip
    easy_install:
      name: pip
      state: latest
    become: true

  - name: install pipenv
    pip:
      name: pipenv
    become: true

  - name: copy benchmark scripts
    copy:
      src: "{{ item }}"
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
    with_fileglob:
      - "{{ playbook_dir }}/sqs-bench-*.py"
    tags:
      - code

  - name: copy pipfile
    copy:
      src: "{{ playbook_dir }}/Pipfile"
      dest: /home/ubuntu/Pipfile
      owner: ubuntu
      group: ubuntu
    tags:
      - code

  - name: pipenv install
    command: pipenv install
    environment:
      PATH: /home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LC_ALL: C.UTF-8
      PIPENV_NOSPIN: 1
      PIPENV_YES: 1
      PIPENV_COLORBLIND: 1
    tags:
      - code

  - name: ensure /home/ubuntu/.aws dir exists
    file: path=/home/ubuntu/.aws state=directory

  - name: copy aws_config
    copy:
      src: "{{ playbook_dir }}/aws_config"
      dest: /home/ubuntu/.aws/config
      owner: ubuntu
      group: ubuntu

