# Add this snippet to the top of your playbook.
# It will install python2 if missing (but checks first so no expensive repeated apt updates)
# gwillem@gmail.com

- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  - name: install atop
    raw: test -e /usr/bin/atop || (sudo apt -y update && sudo apt install -y atop)

  - name: install pip
    raw: test -e /usr/bin/pip || (sudo apt -y update && sudo apt install -y python-pip)

  - pip:
      name: pipenv

  - copy:
      src: "{{ playbook_dir }}/sqs-bench-twisted.py"
      dest: /home/ubuntu/sqs-bench-twisted.py
      owner: ubuntu
      group: ubuntu
    tags:
      - code

  - copy:
      src: "{{ playbook_dir }}/Pipfile"
      dest: /home/ubuntu/Pipfile
      owner: ubuntu
      group: ubuntu
    tags:
      - code

  - name: pipenv install
    command: pipenv install
    environment:
      PATH: /home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LC_ALL: C.UTF-8
      PIPENV_NOSPIN: 1
      PIPENV_YES: 1
      PIPENV_COLORBLIND: 1
    tags:
      - code

  - name: Ensures /home/ubuntu/.aws dir exists
    file: path=/home/ubuntu/.aws state=directory

  - copy:
      src: "{{ playbook_dir }}/aws_config"
      dest: /home/ubuntu/.aws/config
      owner: ubuntu
      group: ubuntu

